services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bsn
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - bsn-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - bsn-network

networks:
  bsn-network:
    driver: bridge

volumes:
  postgres:
    driver: local
